#!/usr/bin/env python3
"""Generate (or verify) the cross-language golden fixture.

The fixture in shared/golden/golden_rollup.json is the contract the Kotlin rollup is
tested against. Regenerating it must be deliberate and visible in a diff — if Python's
output drifts unnoticed, the Kotlin parity test happily keeps passing against the new
wrong answer.

    python tools/gen_golden.py           # write
    python tools/gen_golden.py --check   # fail if the committed file is stale (CI)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "training" / "src"))
sys.path.insert(0, str(REPO / "training" / "tests"))

from test_rollup import build_beetles  # noqa: E402

from lifelist_train.rollup import rollup  # noqa: E402

OUT = REPO / "shared" / "golden" / "golden_rollup.json"

CASES: list[tuple[str, list[float], float]] = [
    ("stops_at_genus", [0.40, 0.38, 0.12, 0.10], 0.70),
    ("descends_to_species", [0.85, 0.05, 0.05, 0.05], 0.70),
    ("unidentified", [0.25, 0.20, 0.05, 0.50], 0.70),
    ("threshold_boundary", [0.40, 0.30, 0.20, 0.10], 0.70),
    ("loose_threshold", [0.40, 0.38, 0.12, 0.10], 0.50),
]


def build() -> dict:
    tax = build_beetles()
    cases = []
    for name, p, threshold in CASES:
        r = rollup(tax, np.array(p, dtype=np.float32), threshold=threshold)
        cases.append(
            {
                "name": name,
                "leaf_probabilities": p,
                "threshold": threshold,
                "expected": {
                    "taxon_id": r.taxon_id,
                    "rank": r.rank,
                    "probability": round(r.probability, 7),
                    "candidates": [
                        {
                            "taxon_id": c.taxon_id,
                            "leaf_index": c.leaf_index,
                            "probability": round(c.probability, 7),
                        }
                        for c in r.candidates
                    ],
                },
            }
        )
    return {
        "spec_version": 1,
        "note": (
            "Generated by training/tools/gen_golden.py. Kotlin must reproduce these "
            "exactly. See shared/taxonomy-spec.md §5.1."
        ),
        "taxonomy": tax.to_dict(),
        "cases": cases,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()

    fresh = json.dumps(build(), indent=2) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"missing {OUT}", file=sys.stderr)
            return 1
        if OUT.read_text() != fresh:
            print(
                f"{OUT} is stale — the rollup's output changed.\n"
                "If that change was intended, run `python tools/gen_golden.py` and commit "
                "the diff so the Kotlin side is updated in the same breath.",
                file=sys.stderr,
            )
            return 1
        print("golden fixture in sync")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
