"""The assets the APK actually ships, checked as data rather than trusted.

`shared/model/taxonomy.json` is generated by a run that lives outside this repo, which is
exactly how it shipped with `vernacular_en` null on all 4,657 nodes: nothing here looked.
The result screen fell through to the scientific name for its headline and then printed the
same name again underneath, and the first person to notice was the person using the app.

These are cheap and they are not unit tests of anything — they are a tripwire on the one
artefact that is built by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TAXONOMY = ROOT / "shared" / "model" / "taxonomy.json"

pytestmark = pytest.mark.skipif(
    not TAXONOMY.exists(), reason="no shipped taxonomy in this checkout"
)


@pytest.fixture(scope="module")
def nodes() -> list[dict]:
    return json.loads(TAXONOMY.read_text(encoding="utf-8"))


def test_every_node_has_the_fields_the_app_reads(nodes):
    required = {"taxon_id", "parent_id", "rank", "scientific_name", "vernacular_en"}
    for node in nodes:
        missing = required - set(node)
        assert not missing, f"{node.get('scientific_name')} is missing {missing}"


def test_most_species_carry_an_english_common_name(nodes):
    """The headline. Below about 80% the screen is Latin more often than not."""
    species = [n for n in nodes if n["rank"] in ("species", "species_aggregate")]
    named = [n for n in species if n.get("vernacular_en")]
    assert len(named) / len(species) > 0.80, (
        f"only {len(named)}/{len(species)} species have an English name — "
        "the taxonomy was probably rebuilt without vernaculars again"
    )


def test_higher_ranks_carry_common_names_too(nodes):
    """A family-level answer is the interesting one, so it is the one that must read well."""
    families = [n for n in nodes if n["rank"] == "family"]
    named = [n for n in families if n.get("vernacular_en")]
    assert len(named) / len(families) > 0.60


def test_common_names_start_with_a_capital(nodes):
    """GBIF hands back whatever case the contributing checklist used."""
    lower = [
        n["vernacular_en"] for n in nodes
        if n.get("vernacular_en") and n["vernacular_en"][0].islower()
    ]
    assert not lower[:5], f"uncapitalised common names, e.g. {lower[:5]}"


def test_indeterminate_leaves_inherit_their_genus_name(nodes):
    """`Carabus sp.` is a ground beetle, and saying so is the whole point of §1.1a."""
    by_id = {n["taxon_id"]: n for n in nodes}
    for node in nodes:
        if node["taxon_id"] < 0:
            parent = by_id.get(node["parent_id"])
            if parent and parent.get("vernacular_en"):
                assert node.get("vernacular_en") == parent["vernacular_en"]


WIKIPEDIA = ROOT / "shared" / "model" / "wikipedia.json"


@pytest.fixture(scope="module")
def articles() -> dict:
    if not WIKIPEDIA.exists():
        pytest.skip("no bundled Wikipedia index in this checkout")
    return json.loads(WIKIPEDIA.read_text(encoding="utf-8"))


def test_most_taxa_have_a_bundled_article(nodes, articles):
    """96% when built correctly. Anything near 80% means the extracts cap bit again (§31)."""
    covered = sum(1 for n in nodes if str(n["taxon_id"]) in articles)
    assert covered / len(nodes) > 0.90, (
        f"only {covered}/{len(nodes)} taxa have an article — "
        "check limits.extracts and the absent cache before believing it"
    )


def test_the_obvious_ones_are_there(nodes, articles):
    """A regression test named after the bird it was written for."""
    by_name = {n["scientific_name"]: n for n in nodes}
    for name in ("Anas platyrhynchos", "Vulpes vulpes", "Carabidae"):
        node = by_name.get(name)
        if node is None:
            continue
        article = articles.get(str(node["taxon_id"]))
        assert article, f"{name} has no bundled article"
        assert name.split(" ")[0].lower() in article["extract"].lower()


def test_every_article_has_the_three_fields_the_app_reads(articles):
    for key, article in list(articles.items())[:200]:
        assert set(article) >= {"title", "extract", "url"}, key
        assert article["extract"].strip()
        assert article["url"].startswith("https://en.wikipedia.org/wiki/")
